config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'ask', to: 'questions#ask'
  get 'answer', to: 'questions#answer'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def poss_answer(question)
    if question == 'I am going to work'
      @answer = 'Great!'
    elsif question.ends_with?('?')
      @answer = 'Silly question, get dressed and go to work!'
    else
      @answer = "I don't care, get dressed and go to work!"
    end
  end

  def ask
  end

  def answer
    @answer = poss_answer(params[:question])
    @answer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<h1>Stupid Coaching</h1>
<p><%= params[:question] %></p>
<p>--You</p>
<p><%= @answer %></p>
<p>--Your coach</p>
<%= link_to "Ask a new question", ask_path %>

app/views/questions/ask.html.erb
<h1>Questions#ask</h1>
<p>Find me in app/views/questions/ask.html.erb</p>
<form action="/answer">
  <input type="text" name="question">
  <input type="submit" value="Ask!">
</form>